# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    c66-slave-ff632c10-2.novalocal
#BUILDTIME:    Wed May 31 03:44:45 2017
#SOURCERPM:    hadoop_2_6_1_0_129-2.7.3.2.6.1.0-129.src.rpm

#RPMVERSION:   4.8.0



#OS:           linux
#SIZE:           6700
#ARCHIVESIZE:           7196
#ARCH:         x86_64
BuildArch:     x86_64
Name:          hadoop_2_6_1_0_129-httpfs-server
Version:       2.7.3.2.6.1.0
Release:       129
License:       Apache License v2.0 
Group:         System/Daemons
Summary:       init.d script for HTTPFS for Hadoop


URL:           http://hadoop.apache.org/core/







Provides:      hadoop_2_6_1_0_129-httpfs-server = 2.7.3.2.6.1.0-129
Provides:      hadoop_2_6_1_0_129-httpfs-server(x86-64) = 2.7.3.2.6.1.0-129
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
Requires:      /bin/bash  
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
#suggest
#enhance
%description
Provides init script for HTTPFS server.
%files
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/etc/rc.d/init.d/hadoop-httpfs"
%attr(0600, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/usr/lib/systemd/system/hadoop-httpfs.service"
%changelog
