# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    c66-slave-ff632c10-2.novalocal
#BUILDTIME:    Wed May 31 03:44:45 2017
#SOURCERPM:    hadoop_2_6_1_0_129-2.7.3.2.6.1.0-129.src.rpm

#RPMVERSION:   4.8.0



#OS:           linux
#SIZE:           38604840
#ARCHIVESIZE:           38662948
#ARCH:         x86_64
BuildArch:     x86_64
Name:          hadoop_2_6_1_0_129-httpfs
Version:       2.7.3.2.6.1.0
Release:       129
License:       Apache License v2.0 
Group:         System/Daemons
Summary:       HTTPFS for Hadoop


URL:           http://hadoop.apache.org/core/







Provides:      hadoop_2_6_1_0_129-httpfs = 2.7.3.2.6.1.0-129
Provides:      hadoop_2_6_1_0_129-httpfs(x86-64) = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-hdfs = 2.7.3.2.6.1.0-129
Requires:      bigtop-tomcat  
Requires:      hadoop_2_6_1_0_129 = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-hdfs = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-httpfs-server = 2.7.3.2.6.1.0-129
Requires:      /bin/sh  
Requires:      /bin/sh  
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
Requires:      /bin/bash  
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
#suggest
#enhance
%description
The server providing HTTP REST API support for the complete FileSystem/FileContext
interface in HDFS.
%files
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/default/hadoop-httpfs"
%dir %config(noreplace) %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/conf.empty"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/conf.empty/httpfs-env.sh"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/conf.empty/httpfs-log4j.properties"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/conf.empty/httpfs-signature.secret"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/conf.empty/httpfs-site.xml"
%dir %config(noreplace) %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist"
%dir %config(noreplace) %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/catalina.policy"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/catalina.properties"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/context.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/logging.properties"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/server.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/ssl-server.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/tomcat-users.xml"
%config(noreplace) %attr(0644, root, root) "/usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/web.xml"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/etc"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/etc/rc.d"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/etc/rc.d/init.d"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/sbin"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/sbin/httpfs.sh"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/sbin/httpfs.sh.distro"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/usr"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/usr/lib"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/usr/lib/systemd"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/usr/lib/systemd/system"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/ROOT"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/ROOT/WEB-INF"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/ROOT/WEB-INF/web.xml"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/ROOT/index.html"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/META-INF"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/default-log4j.properties"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/httpfs-default.xml"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/httpfs.properties"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$1.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$2.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$3.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$4.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$5.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$FILE_TYPE.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$HttpFSDataInputStream.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$HttpFSDataOutputStream.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem$Operation.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSFileSystem.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpFSUtils.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/client/HttpsFSFileSystem.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/CheckUploadContentTypeFilter.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSAclStatus.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSAppend.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSConcat.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSContentSummary.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSCreate.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSDelete.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSFileChecksum.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSFileStatus.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSGetXAttrs.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSHomeDir.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSListStatus.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSListXAttrs.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSMkdirs.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSModifyAclEntries.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSOpen.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRemoveAcl.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRemoveAclEntries.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRemoveDefaultAcl.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRemoveXAttr.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSRename.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetAcl.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetOwner.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetPermission.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetReplication.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetTimes.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSSetXAttr.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$FSTruncate.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$StatusPair.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations$StatusPairs.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/FSOperations.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSAuthenticationFilter.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSExceptionProvider.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$AccessTimeParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$AclPermissionParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$BlockSizeParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$DataParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$DestinationParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$FilterParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$GroupParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$LenParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$ModifiedTimeParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$NewLengthParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$OffsetParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$OperationParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$OverwriteParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$OwnerParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$PermissionParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$RecursiveParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$ReplicationParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$SourcesParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$XAttrEncodingParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$XAttrNameParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$XAttrSetFlagParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider$XAttrValueParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSParametersProvider.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSReleaseFilter.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSServer$1.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSServer$2.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSServer.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/fs/http/server/HttpFSServerWebApp.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/lang"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/lang/RunnableCallable.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/lang/XException$ERROR.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/lang/XException.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/BaseService.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/Server$Status.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/Server.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/ServerException$ERROR.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/ServerException.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/Service.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/server/ServiceException.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/FileSystemAccess$FileSystemExecutor.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/FileSystemAccess.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/FileSystemAccessException$ERROR.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/FileSystemAccessException.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Groups.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Instrumentation$Cron.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Instrumentation$Variable.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Instrumentation.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/Scheduler.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$1.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$2.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$3.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$4.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$CachedFileSystem.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService$FileSystemCachePurger.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/hadoop/FileSystemAccessService.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$1.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$2.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$3.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$Cron.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$Sampler.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$SamplersRunnable.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$Timer.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService$VariableHolder.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/instrumentation/InstrumentationService.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/scheduler"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/scheduler/SchedulerService$1.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/scheduler/SchedulerService.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/security"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/service/security/GroupsService.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet/FileSystemReleaseFilter.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet/HostnameFilter.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet/MDCFilter.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/servlet/ServerWebApp.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/util"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/util/Check.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/util/ConfigurationUtils.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/BooleanParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/ByteParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/EnumParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/EnumSetParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/ExceptionProvider.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/InputStreamEntity.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/IntegerParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/JSONMapProvider.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/JSONProvider.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/LongParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/Param.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/Parameters.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/ParametersProvider.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/ShortParam.class"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/classes/org/apache/hadoop/lib/wsrs/StringParam.class"
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/activation-1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/apacheds-i18n-2.0.0-M15.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/apacheds-kerberos-codec-2.0.0-M15.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/api-asn1-api-1.0.0-M20.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/api-util-1.0.0-M20.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/asm-3.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/avro-1.7.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/azure-keyvault-core-0.8.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/azure-storage-4.2.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-beanutils-1.7.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-beanutils-core-1.8.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-cli-1.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-codec-1.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-collections-3.2.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-compress-1.4.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-configuration-1.6.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-daemon-1.0.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-digester-1.8.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-io-2.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-lang-2.6.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-lang3-3.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-logging-1.1.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-math3-3.1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/commons-net-3.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/curator-client-2.7.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/curator-framework-2.7.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/curator-recipes-2.7.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/gson-2.2.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/guava-11.0.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/hadoop-annotations-2.7.3.2.6.1.0-129.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/hadoop-auth-2.7.3.2.6.1.0-129.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/hadoop-common-2.7.3.2.6.1.0-129.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/hadoop-hdfs-2.7.3.2.6.1.0-129.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/htrace-core-3.1.0-incubating.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/httpclient-4.5.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/httpcore-4.4.4.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jackson-annotations-2.2.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jackson-core-2.2.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jackson-core-asl-1.9.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jackson-databind-2.2.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jackson-jaxrs-1.9.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jackson-mapper-asl-1.9.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jackson-xc-1.9.13.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jaxb-api-2.2.2.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jaxb-impl-2.2.3-1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jcip-annotations-1.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jersey-core-1.9.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jersey-json-1.9.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jersey-server-1.9.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jettison-1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jetty-sslengine-6.1.26.hwx.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jline-0.9.94.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jsch-0.1.54.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/json-simple-1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/json-smart-1.1.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/jsr305-3.0.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/leveldbjni-all-1.8.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/log4j-1.2.17.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/netty-3.6.2.Final.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/netty-all-4.0.23.Final.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/nimbus-jose-jwt-3.9.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/okhttp-2.4.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/okio-1.4.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/paranamer-2.3.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/protobuf-java-2.5.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/slf4j-api-1.7.10.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/slf4j-log4j12-1.7.10.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/snappy-java-1.0.4.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/xercesImpl-2.9.1.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/xml-apis-1.3.04.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/xmlenc-0.52.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/xz-1.0.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/lib/zookeeper-3.4.6.2.6.1.0-129.jar"
%attr(0644, root, root) "/usr/hdp/2.6.1.0-129/hadoop-httpfs/webapps/webhdfs/WEB-INF/web.xml"
%attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/libexec/httpfs-config.sh"
%pre -p /bin/sh
getent group httpfs >/dev/null   || groupadd -r httpfs
getent passwd httpfs >/dev/null || /usr/sbin/useradd --comment "Hadoop HTTPFS" --shell /bin/bash -M -r -g httpfs -G hadoop --home /var/lib/hadoop-httpfs httpfs

if [[ ! -e "/var/log/hadoop-httpfs" ]]; then
    /usr/bin/install -d -o httpfs -g hadoop -m 0775  /var/log/hadoop-httpfs
fi

if [[ ! -e "/var/run/hadoop-httpfs" ]]; then
    /usr/bin/install -d -o httpfs -g hadoop -m 0775  /var/run/hadoop-httpfs
fi

if [[ ! -e "/var/lib/hadoop-httpfs" ]]; then
    /usr/bin/install -d -o httpfs -g hadoop -m 0755  /var/lib/hadoop-httpfs
fi

if [[ ! -e "/var/lib/hadoop-httpfs/cache" ]]; then
    /usr/bin/install -d -o httpfs -g hadoop -m 1777  /var/lib/hadoop-httpfs/cache
fi
%post -p /bin/sh
if [ !  -e "/etc/hadoop-httpfs/conf" ]; then
    rm -f /etc/hadoop-httpfs/conf
    mkdir -p /etc/hadoop-httpfs/conf
    cp -rp /usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/conf.empty/* /etc/hadoop-httpfs/conf

    rm -rf /etc/hadoop-httpfs/tomcat-deployment/conf
    mkdir -p /etc/hadoop-httpfs/tomcat-deployment/conf
    cp -rp /usr/hdp/2.6.1.0-129/etc/hadoop-httpfs/tomcat-deployment.dist/conf/* /etc/hadoop-httpfs/tomcat-deployment/conf
    ln -sf /usr/lib/bigtop-tomcat/lib /etc/hadoop-httpfs/tomcat-deployment/lib
    ln -sf /usr/lib/bigtop-tomcat/bin /etc/hadoop-httpfs/tomcat-deployment/bin
    chown -R httpfs:hadoop /etc/hadoop-httpfs/tomcat-deployment/
fi
# systemd
if [[ $(ps --no-headers -o comm 1) = "systemd" ]]; then
   [ -d /usr/lib/systemd/system ] || mkdir -p /usr/lib/systemd/system
   [ -L /usr/lib/systemd/system/hadoop-httpfs.service ] && rm -f /usr/lib/systemd/system/hadoop-httpfs.service
   ln -sf /usr/hdp/current/hadoop-httpfs//usr/lib/systemd/system/hadoop-httpfs.service /usr/lib/systemd/system/hadoop-httpfs.service
   systemctl daemon-reload
fi
/usr/bin/hdp-select --rpm-mode set hadoop-httpfs 2.6.1.0-129
%changelog
