# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    c66-slave-ff632c10-2.novalocal
#BUILDTIME:    Wed May 31 03:44:45 2017
#SOURCERPM:    hadoop_2_6_1_0_129-2.7.3.2.6.1.0-129.src.rpm

#RPMVERSION:   4.8.0



#OS:           linux
#SIZE:           0
#ARCHIVESIZE:           36704
#ARCH:         x86_64
BuildArch:     x86_64
Name:          hadoop_2_6_1_0_129-client
Version:       2.7.3.2.6.1.0
Release:       129
License:       Apache License v2.0 
Group:         System/Daemons
Summary:       Hadoop client side dependencies


URL:           http://hadoop.apache.org/core/







Provides:      hadoop_2_6_1_0_129-client = 2.7.3.2.6.1.0-129
Provides:      hadoop_2_6_1_0_129-client(x86-64) = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129 = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-hdfs = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-yarn = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-mapreduce = 2.7.3.2.6.1.0-129
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
#suggest
#enhance
%description
Installation of this package will provide you with all the dependencies for Hadoop clients.
%files
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/activation-1.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/activation.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/apacheds-i18n-2.0.0-M15.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/apacheds-i18n.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/apacheds-kerberos-codec-2.0.0-M15.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/apacheds-kerberos-codec.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/api-asn1-api-1.0.0-M20.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/api-asn1-api.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/api-util-1.0.0-M20.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/api-util.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/avro-1.7.4.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/avro.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/azure-keyvault-core-0.8.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/azure-keyvault-core.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/azure-storage-4.2.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/azure-storage.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-beanutils-1.7.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-beanutils-core-1.8.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-beanutils-core.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-beanutils.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-cli-1.2.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-cli.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-codec-1.4.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-codec.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-collections-3.2.2.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-collections.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-compress-1.4.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-compress.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-configuration-1.6.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-configuration.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-digester-1.8.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-digester.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-io-2.4.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-io.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-lang-2.6.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-lang.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-lang3-3.4.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-lang3.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-logging-1.1.3.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-logging.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-math3-3.1.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-math3.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-net-3.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/commons-net.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/curator-client-2.7.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/curator-client.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/curator-framework-2.7.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/curator-framework.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/curator-recipes-2.7.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/curator-recipes.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/gson-2.2.4.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/gson.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/guava-11.0.2.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/guava.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-annotations-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-annotations.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-auth-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-auth.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-common-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-common.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-hdfs-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-hdfs.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-app-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-app.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-common-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-common.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-core-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-core.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-jobclient-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-jobclient.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-shuffle-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-mapreduce-client-shuffle.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-api-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-api.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-client-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-client.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-common-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-common.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-registry-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-registry.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-server-common-2.7.3.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-server-common.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/htrace-core-3.1.0-incubating.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/htrace-core.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/httpclient-4.5.2.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/httpclient.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/httpcore-4.4.4.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/httpcore.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-annotations-2.2.3.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-annotations.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-core-2.2.3.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-core-asl-1.9.13.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-core-asl.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-core.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-databind-2.2.3.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-databind.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-jaxrs-1.9.13.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-jaxrs.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-mapper-asl-1.9.13.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-mapper-asl.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-xc-1.9.13.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jackson-xc.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jaxb-api-2.2.2.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jaxb-api.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jcip-annotations-1.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jcip-annotations.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jersey-client-1.9.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jersey-client.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jersey-core-1.9.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jersey-core.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jetty-sslengine-6.1.26.hwx.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jetty-sslengine.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jetty-util-6.1.26.hwx.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jetty-util.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/json-smart-1.1.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/json-smart.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jsp-api-2.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jsp-api.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jsr305-3.0.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/jsr305.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/leveldbjni-all-1.8.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/leveldbjni-all.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/log4j-1.2.17.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/log4j.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/netty-3.6.2.Final.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/netty-all-4.0.23.Final.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/netty-all.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/netty.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/nimbus-jose-jwt-3.9.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/nimbus-jose-jwt.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/okhttp-2.4.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/okhttp.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/okio-1.4.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/okio.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/paranamer-2.3.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/paranamer.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/protobuf-java-2.5.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/protobuf-java.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/servlet-api-2.5.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/servlet-api.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/slf4j-api-1.7.10.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/slf4j-api.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/slf4j-log4j12-1.7.10.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/slf4j-log4j12.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/snappy-java-1.0.4.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/snappy-java.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/stax-api-1.0-2.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/stax-api.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/xercesImpl-2.9.1.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/xercesImpl.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/xml-apis-1.3.04.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/xml-apis.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/xmlenc-0.52.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/xmlenc.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/xz-1.0.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/xz.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/zookeeper-3.4.6.2.6.1.0-129.jar"
%attr(0777, root, root) "/usr/hdp/2.6.1.0-129/hadoop/client/zookeeper.jar"
%changelog
