# rpmrebuild autogenerated specfile

AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    c66-slave-ff632c10-2.novalocal
#BUILDTIME:    Wed May 31 03:44:45 2017
#SOURCERPM:    hadoop_2_6_1_0_129-2.7.3.2.6.1.0-129.src.rpm

#RPMVERSION:   4.8.0



#OS:           linux
#SIZE:           0
#ARCHIVESIZE:           36704
#ARCH:         x86_64
BuildRoot:     /root/.tmp/rpmrebuild.12550/work/root
BuildArch:     x86_64
Name:          hadoop_2_6_1_0_129-client
Version:       2.7.3.2.6.1.0
Release:       129
License:       Apache License v2.0 
Group:         System/Daemons
Summary:       Hadoop client side dependencies


URL:           http://hadoop.apache.org/core/







Provides:      hadoop_2_6_1_0_129-client = 2.7.3.2.6.1.0-129
Provides:      hadoop_2_6_1_0_129-client(x86-64) = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129 = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-hdfs = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-yarn = 2.7.3.2.6.1.0-129
Requires:      hadoop_2_6_1_0_129-mapreduce = 2.7.3.2.6.1.0-129
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
#suggest
#enhance
%description
Installation of this package will provide you with all the dependencies for Hadoop clients.
%files
%dir %attr(0755, root, root) /usr/hdp/2.6.1.0-129/hadoop/client
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jsr311-api-1.1.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-server-common-3.0.2-SNAPSHOT.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/curator-framework-2.12.0.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jetty-http-9.3.19.v20170502.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/paranamer-2.3.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-core-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jettison-1.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jersey-server-1.19.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-auth.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-annotations-3.0.2-SNAPSHOT.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/slf4j-api-1.7.25.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jcip-annotations-1.0-1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jackson-core-asl-1.9.13.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/woodstox-core-5.0.3.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/junit-4.11.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-annotations.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-math3-3.1.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-common-3.0.2-SNAPSHOT.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/nimbus-jose-jwt-4.41.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jackson-jaxrs-1.9.13.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/zookeeper-3.4.9.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/gson-2.2.4.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/protobuf-java-2.5.0.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jsch-0.1.54.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-io-2.4.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/snappy-java-1.0.5.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jetty-servlet-9.3.19.v20170502.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-util-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/mockito-all-1.8.5.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerby-pkix-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/curator-client-2.12.0.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-collections-3.2.2.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jaxb-impl-2.2.3-1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/asm-5.0.4.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/netty-3.10.5.Final.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jetty-server-9.3.19.v20170502.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/httpcore-4.4.4.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-compress-1.4.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jetty-security-9.3.19.v20170502.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-registry-3.0.2-SNAPSHOT.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jetty-webapp-9.3.19.v20170502.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jersey-json-1.19.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jetty-io-9.3.19.v20170502.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/htrace-core4-4.1.0-incubating.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/curator-recipes-2.12.0.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-common-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/accessors-smart-1.2.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jackson-mapper-asl-1.9.13.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-api-3.0.2-SNAPSHOT.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/xz-1.0.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-client-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-logging-1.1.3.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-auth-3.0.2-SNAPSHOT.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jaxb-api-2.2.11.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jackson-core-2.7.8.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/avro-1.7.7.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jsr305-3.0.0.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/slf4j-log4j12-1.7.25.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerby-util-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/stax2-api-3.1.4.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerby-asn1-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/guava-11.0.2.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jersey-servlet-1.19.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-server-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jackson-databind-2.7.8.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/token-provider-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-common-3.0.2-SNAPSHOT.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/metrics-core-3.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-admin-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/log4j-1.2.17.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerby-config-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jackson-xc-1.9.13.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerby-xdr-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jetty-xml-9.3.19.v20170502.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jersey-core-1.19.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-lang3-3.4.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jackson-annotations-2.7.8.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-net-3.6.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-simplekdc-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-lang-2.6.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-configuration2-2.1.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/re2j-1.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jetty-util-9.3.19.v20170502.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-beanutils-1.9.3.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-codec-1.4.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-common.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hamcrest-core-1.3.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/json-smart-2.3.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/commons-cli-1.2.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-crypto-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/hadoop-yarn-client-3.0.2-SNAPSHOT.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/javax.servlet-api-3.1.0.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jul-to-slf4j-1.7.25.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/jsp-api-2.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/kerb-identity-1.0.1.jar
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/client/httpclient-4.5.2.jar
%changelog
