# rpmrebuild autogenerated specfile

AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    ip-10-8-105-156
#BUILDTIME:    Sun Mar  4 00:57:38 2018
#SOURCERPM:    hadoop_2_6_1_0_129-2.7.3.2.6.1.0-129.src.rpm

#RPMVERSION:   4.11.3



#OS:           linux
#SIZE:           244699786
#ARCHIVESIZE:           244725720
#ARCH:         x86_64
BuildRoot:     /root/hadoop/hadoop-dist/target/rpm
BuildArch:     x86_64
Name:          hadoop_2_6_1_0_129
Version:       2.7.3.2.6.1.0
Release:       129
License:       Apache License v2.0 
Group:         Development/Libraries
Summary:       Hadoop is a software platform for processing vast amounts of data
Distribution:  Amazon Linux AMI

URL:           http://hadoop.apache.org/core/







Provides:      libhadoop.so.1.0.0()(64bit)  
Provides:      libsnappy.so.1()(64bit)  
Provides:      hadoop_2_6_1_0_129 = 2.7.3.2.6.1.0-129
Provides:      hadoop_2_6_1_0_129(x86-64) = 2.7.3.2.6.1.0-129
Requires:      coreutils  
Requires:      /usr/sbin/useradd  
Requires:      /usr/sbin/usermod  
Requires:      /sbin/chkconfig  
Requires:      /sbin/service  
Requires:      zookeeper_2_6_1_0_129 >= 3.4.0
Requires:      ranger_2_6_1_0_129-hdfs-plugin  
Requires:      ranger_2_6_1_0_129-yarn-plugin  
Requires:      hdp-select >= 2.6.1.0-129
Requires:      spark_2_6_1_0_129-yarn-shuffle  
Requires:      spark2_2_6_1_0_129-yarn-shuffle  
Requires:      psmisc  
Requires:      nc  
Requires:      sh-utils  
Requires:      redhat-lsb-core  
Requires:      /bin/sh  
Requires:      /bin/sh  
Requires:      /bin/sh  
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#suggest
#enhance
%description
Hadoop is a software platform that lets one easily write and
run applications that process vast amounts of data.

Here's what makes Hadoop especially useful:
* Scalable: Hadoop can reliably store and process petabytes.
* Economical: It distributes the data and processing across clusters
              of commonly available computers. These clusters can number
              into the thousands of nodes.
* Efficient: By distributing the data, Hadoop can process it in parallel
             on the nodes where the data is located. This makes it
             extremely rapid.
* Reliable: Hadoop automatically maintains multiple copies of data and
            automatically redeploys computing tasks based on failures.

Hadoop implements MapReduce, using the Hadoop Distributed File System (HDFS).
MapReduce divides applications into many small blocks of work. HDFS creates
multiple replicas of data blocks for reliability, placing them on compute
nodes around the cluster. MapReduce can then process the data where it is
located.
%files
%attr(0755, root, root) /usr/hdp/2.6.1.0-129/hadoop
%attr(0777, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-auth.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-common-sources.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-annotations-3.0.2-SNAPSHOT.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-annotations.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-aws.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-common-3.0.2-SNAPSHOT-sources.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-common-test-sources.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-common-3.0.2-SNAPSHOT-test-sources.jar
%dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/bin
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/bin/hadoop
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/bin/container-executor
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/bin/hdfs.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/bin/mapred.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/bin/test-container-executor
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/bin/yarn.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/bin/hadoop.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-auth-3.0.2-SNAPSHOT.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-common-tests.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-nfs-3.0.2-SNAPSHOT.jar
%dir %attr(0755, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jsr311-api-1.1.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/curator-framework-2.12.0.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jetty-http-9.3.19.v20170502.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/paranamer-2.3.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-core-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jettison-1.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jersey-server-1.19.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/hadoop-annotations-3.0.2-SNAPSHOT.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/slf4j-api-1.7.25.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jcip-annotations-1.0-1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jackson-core-asl-1.9.13.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/woodstox-core-5.0.3.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/junit-4.11.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-math3-3.1.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/nimbus-jose-jwt-4.41.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jackson-jaxrs-1.9.13.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/zookeeper-3.4.9.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/gson-2.2.4.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/protobuf-java-2.5.0.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jsch-0.1.54.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-io-2.4.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/snappy-java-1.0.5.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jetty-servlet-9.3.19.v20170502.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-util-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/mockito-all-1.8.5.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerby-pkix-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/curator-client-2.12.0.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-collections-3.2.2.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jaxb-impl-2.2.3-1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/asm-5.0.4.jar
%dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/examples
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/examples/wordcount-simple
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/examples/pipes-sort
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/examples/wordcount-part
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/examples/wordcount-nopipe
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libnativetask.so.1.0.0
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadoop.so.1.0.0
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libnativetask.so
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadoop.a
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libhdfs.so.0.0.0
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libhdfs.so
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadooppipes.a
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadoop.so
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libhdfs.a
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libnativetask.a
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/native/libhadooputils.a
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/netty-3.10.5.Final.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jetty-server-9.3.19.v20170502.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/httpcore-4.4.4.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-compress-1.4.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jetty-security-9.3.19.v20170502.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jetty-webapp-9.3.19.v20170502.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jersey-json-1.19.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jetty-io-9.3.19.v20170502.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/htrace-core4-4.1.0-incubating.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/curator-recipes-2.12.0.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-common-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/accessors-smart-1.2.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jackson-mapper-asl-1.9.13.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/xz-1.0.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-client-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-logging-1.1.3.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/hadoop-auth-3.0.2-SNAPSHOT.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jaxb-api-2.2.11.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jackson-core-2.7.8.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/avro-1.7.7.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jsr305-3.0.0.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/slf4j-log4j12-1.7.25.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerby-util-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/stax2-api-3.1.4.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerby-asn1-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/guava-11.0.2.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jersey-servlet-1.19.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-server-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jackson-databind-2.7.8.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/token-provider-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/metrics-core-3.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-admin-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/log4j-1.2.17.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerby-config-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jackson-xc-1.9.13.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerby-xdr-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jetty-xml-9.3.19.v20170502.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jersey-core-1.19.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-lang3-3.4.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jackson-annotations-2.7.8.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-net-3.6.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-simplekdc-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-lang-2.6.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-configuration2-2.1.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/re2j-1.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jetty-util-9.3.19.v20170502.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-beanutils-1.9.3.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-codec-1.4.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/hamcrest-core-1.3.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/json-smart-2.3.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/commons-cli-1.2.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-crypto-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/javax.servlet-api-3.1.0.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jul-to-slf4j-1.7.25.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/jsp-api-2.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/kerb-identity-1.0.1.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/lib/httpclient-4.5.2.jar
%dir %attr(0755, root, root) "/usr/hdp/2.6.1.0-129/hadoop/etc"
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-nfs.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-common-3.0.2-SNAPSHOT.jar
%dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/yarn-config.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/hdfs-config.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/hadoop-functions.sh
%dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-archive-logs.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-distcp.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-rumen.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-archives.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-extras.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-resourceestimator.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-gridmix.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-streaming.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-sls.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/tools/hadoop-aws.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/mapred-config.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/hadoop-layout.sh.example
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/hadoop-config.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/hadoop-config.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-azure.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-yarn.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-archive-logs.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-mapreduce.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-hdfs.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-distcp.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-rumen.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-aliyun.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-archives.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-extras.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-azure-datalake.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-kms.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-openstack.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-gridmix.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-streaming.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-httpfs.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-kafka.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-s3guard.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/libexec/shellprofile.d/hadoop-aws.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/mapreduce.tar.gz
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-common-3.0.2-SNAPSHOT-tests.jar
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/conf
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-common.jar
%dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/httpfs.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/stop-all.sh
%dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/SQLServer
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/SQLServer/FederationStateStoreStoreProcs.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/SQLServer/FederationStateStoreTables.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL/FederationStateStoreTables.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL/FederationStateStoreStoredProcs.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL/dropStoreProcedures.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL/dropTables.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL/dropUser.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL/FederationStateStoreUser.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL/FederationStateStoreDatabase.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/FederationStateStore/MySQL/dropDatabase.sql
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/start-balancer.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/start-all.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/stop-yarn.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/start-dfs.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/stop-dfs.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/distribute-exclude.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/hadoop-daemon.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/yarn-daemon.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/stop-secure-dns.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/stop-yarn.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/start-secure-dns.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/start-dfs.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/stop-all.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/refresh-namenodes.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/yarn-daemons.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/workers.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/hadoop-daemons.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/mr-jobhistory-daemon.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/start-all.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/kms.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/start-yarn.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/stop-balancer.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/start-yarn.cmd
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/sbin/stop-dfs.sh
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/hadoop/hadoop-aws-3.0.2-SNAPSHOT.jar
%dir %attr(0755, root, root) /usr/hdp/2.6.1.0-129/etc
%config(noreplace) %dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/user_ec_policies.xml.template
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/ssl-server.xml.example
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-env.sh
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/kms-env.sh
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/mapred-env.cmd
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/core-site.xml
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/yarn-env.cmd
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/kms-log4j.properties
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-env.cmd
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/log4j.properties
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/httpfs-site.xml
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/configuration.xsl
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/workers
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/httpfs-env.sh
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-metrics2.properties
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/httpfs-log4j.properties
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/kms-site.xml
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/shellprofile.d
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/shellprofile.d/example.sh
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-policy.xml
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/kms-acls.xml
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/ssl-client.xml.example
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/httpfs-signature.secret
%config(noreplace) %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/hadoop-user-functions.sh.example
%dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/default
%dir %attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/bash_completion.d
%attr(0775, root, root) /usr/hdp/2.6.1.0-129/etc/bash_completion.d/hadoop
%pre -p /bin/sh
getent group hadoop >/dev/null || groupadd -r hadoop
%post -p /bin/sh
if [ !  -e "/etc/hadoop/conf" ]; then
    rm -f /etc/hadoop/conf
    mkdir -p /etc/hadoop/conf
    cp -rp /usr/hdp/2.6.1.0-129/etc/hadoop/conf.empty/* /etc/hadoop/conf
fi
/usr/bin/hdp-select --rpm-mode set hadoop-client 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-datanode 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-journalnode 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-nfs3 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-namenode 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-portmap 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-secondarynamenode 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-hdfs-zkfc 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-mapreduce-historyserver 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-yarn-resourcemanager 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-yarn-nodemanager 2.6.1.0-129
/usr/bin/hdp-select --rpm-mode set hadoop-yarn-timelineserver 2.6.1.0-129
%changelog
